services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: healthos
    ports:
      - "5432:5432"
    volumes:
      - healthos_pg:/var/lib/postgresql/data
volumes:
  healthos_pg:
